name: Test

on:
  workflow_dispatch

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: coderpatros/action-hello-world@7902eacf3deb66f0ae3ffa5c7a647c053aa61c97
